{% set name = "tangram_snfg" %}


package:
  name: {{ name|lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '0')|int }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
  run:
    - python
    - pychimera     >=0.2.6
    - libtangram

about:
  home: http://github.com/insilichem/tangram_snfg
  license: MIT
  license_family: MIT

  summary: '3D implementation of The Symbol Nomenclature For Glycans (SNFG) for UCSF Chimera '

  description: |
    3D implementation of The Symbol Nomenclature For Glycans (SNFG) for UCSF Chimera
  doc_url: http://tangram-suite.readthedocs.io/en/latest/tangram_snfg.html
  dev_url: https://github.com/insilichem/tangram_snfg


